let sample = [ { videoUrl: 'https://www.youtube.com/watch?v=DpjYk6yZxz4',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/DpjYk6yZxz4/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/DpjYk6yZxz4/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/DpjYk6yZxz4/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/DpjYk6yZxz4/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/DpjYk6yZxz4/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'the-nun-review-spoilers',
description: 'Decided to do my first traditional movie review on The Nun. I figured since I put so much work into those Annabelle videos I kinda had to. Enjoy!\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'DpjYk6yZxz4',
uploaded: '"2018-09-13T19:26:54.000Z"',
duration: '"hours": 0, "minutes": 7, "seconds": 15',
title: 'The Nun Review (spoilers)' },
{ videoUrl: 'https://www.youtube.com/watch?v=V6mKKeR7r44',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/V6mKKeR7r44/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/V6mKKeR7r44/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/V6mKKeR7r44/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/V6mKKeR7r44/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/V6mKKeR7r44/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'top-10-abstract-films-to-watch-if-you-were-intrigued-by-mother',
description: 'In this video I make some film recommendations for those of you looking for some abstract stuff to watch. Enjoy!\n\nCrossing the Threshold - Ghostpocalypse by Kevin MacLeod is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)\nSource: http://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100663\nArtist: http://incompetech.com/\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'V6mKKeR7r44',
uploaded: '"2017-11-03T07:37:51.000Z"',
duration: '"hours": 0, "minutes": 17, "seconds": 20',
title: 'Top 10 Abstract Films to Watch if You Were Intrigued by *Mother!*' },
{ videoUrl: 'https://www.youtube.com/watch?v=TA265kDT4Bk',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/TA265kDT4Bk/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/TA265kDT4Bk/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/TA265kDT4Bk/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/TA265kDT4Bk/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/TA265kDT4Bk/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'mandy-review',
description: 'Here is my review of the new Panos Cosmatos film \' Mandy\' Also I was having some issues with my microphone so I apologize for the lower quality audio. Otherwise Enjoy!',
id: 'TA265kDT4Bk',
uploaded: '"2018-09-28T05:26:22.000Z"',
duration: '"hours": 0, "minutes": 5, "seconds": 36',
title: 'Mandy Review' },
{ videoUrl: 'https://www.youtube.com/watch?v=3YyeHA2aFHo',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/3YyeHA2aFHo/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/3YyeHA2aFHo/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/3YyeHA2aFHo/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/3YyeHA2aFHo/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/3YyeHA2aFHo/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'annabelle-what-happened-part-1',
description: 'So the Annabelle films are pretty odd. In this video I take you guys through why I think the first one is kind of ridiculous. Enjoy! Part 2 coming soon.\n\nAnnabelle is owned by Warner Brothers Pictures\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: '3YyeHA2aFHo',
uploaded: '"2017-11-16T22:29:08.000Z"',
duration: '"hours": 0, "minutes": 24, "seconds": 50',
title: 'Annabelle What Happened?! Part 1' },
{ videoUrl: 'https://www.youtube.com/watch?v=ePyn79j3aAE',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/ePyn79j3aAE/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/ePyn79j3aAE/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/ePyn79j3aAE/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/ePyn79j3aAE/sddefault.jpg","width":640,"height":480}}',
uri: 'what-makes-a-good-horror-film',
description: 'In this video I discuss some of my favorite horror films and why I feel that they are excellent examples of how to do this genre right. Enjoy!\n\nExamining The Jumpscare Ben Gardener\'s Boat - https://www.youtube.com/watch?v=lYoYK761wwc \n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'ePyn79j3aAE',
uploaded: '"2017-08-06T04:42:42.000Z"',
duration: '"hours": 0, "minutes": 16, "seconds": 0',
title: 'What Makes a Good Horror Film?' },
{ videoUrl: 'https://www.youtube.com/watch?v=rThHpX7Sl_4',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/rThHpX7Sl_4/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/rThHpX7Sl_4/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/rThHpX7Sl_4/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/rThHpX7Sl_4/sddefault.jpg","width":640,"height":480}}',
uri: 'the-last-yamcha',
description: 'I couldn\'t help myself...',
id: 'rThHpX7Sl_4',
uploaded: '"2018-08-11T00:42:48.000Z"',
duration: '"hours": 0, "minutes": 0, "seconds": 34',
title: 'The Last Yamcha' },
{ videoUrl: 'https://www.youtube.com/watch?v=JEZf5Io3L2k',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/JEZf5Io3L2k/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/JEZf5Io3L2k/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/JEZf5Io3L2k/hqdefault.jpg","width":480,"height":360}}',
uri: 'the-nature-of-your-reality-artificial-intelligence-supercut',
description: 'I have put together this supercut to pay tribute to the Artificial Intelligence portrayed in film and television over the years. Enjoy :)\n\nFollow Me On:\n\nInstagram: https://www.instagram.com/culleyrose89/\nTwitter: https://twitter.com/RainbowRose89\n\n\nMusic: TFB3- Vibe Tracks\n\nClips used:\n\nWestworld  (2016) (TV Series) - HBO\n\nWestworld  (1973) -MGM\n\nEx Machina (2014) -Universal Pictures International \n\nStar Wars : Episode 7 The force Awakens (2015) - Lucasfilm\n\nBlade Runner (1982) - Warner Bros.\n\n2001 : A Space Odyssey (1968) -MGM\n\nPrometheus (2012) - 20th Century Fox\n\nGhost in the Shell (1995) - Kodansha, Bandai Visual Company\n\nGhost in the Shell (2017) - Arad Productions, Dreamworks \n\nAll is Full of Love Music Video (1999) - Bjork\n\nErgo Proxy (2006) (TV Series) - Geneon Entertainment\n\nAliens (1986) - 20th Century Fox\n\nStar Trek :The Next Generation (TV Series) - Paramount Television \n\nDoomsday Book (2012) - Gio Entertainment\n\nRoboCop (1987) - Orion Pictures\n\nThe Iron Giant (1999) - Warner Bros.\n\nThe Matrix (1999) - Warner Bros.\n\nWALL-E (2008) Pixar, Walt Disney Pictures\n\nThe Terminator (1984) - Hemdale, Pacific Western\n\nTerminator 2 Judgement Day (1991) - Pacific Western, Carolco Pictures\n\nThe Animatrix (2003)- DNA Productions\n\nI, Robot- (2004)- 20thCentury Fox\n\nStar Wars : Episode 4 A New Hope (1977) - Lucasfilm, 20th Century Fox\n\nAvengers : Age of Ultron (2015) - Marvel Studios, Walt Disney\n\nMetropolis (1927) - Universum Film\n\nMoon (2009) - Liberty Films UK\n\nHer (2013) - Annapurna Pictures\n\nRogue One : A Star Wars Story (2016) - Lucasfilm\n\nInterstellar (2014) - Paramount Pictures \n \nA.I Artificial Intelligence (2001) - Warner Bros. Dreamworks\n\nBig O  (1999) (TV Series)- Bandai\n\nShort Circut (1986) - TriStar Pictures\n\nChobits (2002) - Clamp, Madhouse',
id: 'JEZf5Io3L2k',
uploaded: '"2017-03-23T19:57:38.000Z"',
duration: '"hours": 0, "minutes": 3, "seconds": 51',
title: 'The Nature Of Your Reality (Artificial Intelligence Supercut)' },
{ videoUrl: 'https://www.youtube.com/watch?v=kDeNTDGOVws',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/kDeNTDGOVws/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/kDeNTDGOVws/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/kDeNTDGOVws/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/kDeNTDGOVws/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/kDeNTDGOVws/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'the-witch-explained-sins-of-the-father',
description: 'Hey everyone this was supposed to be out in October but I ran into some difficulties but just because Halloween is over doesn\'t mean you can\'t still binge a bunch of horror films. If you happen to come across Robert Eggers\' horror masterpiece, The Witch and you need a little help grasping it, I got you. In this video I go into my personal interpretation of this film and I hope you enjoy :)\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'kDeNTDGOVws',
uploaded: '"2018-11-01T20:53:03.000Z"',
duration: '"hours": 0, "minutes": 17, "seconds": 26',
title: 'The Witch Explained - Sins of the Father' },
{ videoUrl: 'https://www.youtube.com/watch?v=lYoYK761wwc',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/lYoYK761wwc/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/lYoYK761wwc/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/lYoYK761wwc/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/lYoYK761wwc/sddefault.jpg","width":640,"height":480}}',
uri: 'examining-the-jump-scare-case-study-jaws-ben-gardner-s-boat',
description: 'In this video I examine why the Ben Gardner\'s Boat jump scare from the 1975 film Jaws is so effective. \n\nA couple of errors in my narration I\'de like to address in this video I didn\'t notice until it was too late. At one point I say Ben Gardener\'s head is "severed" when It actually is not. Totally a neck and shoulders there. Also the the chum throwing scene isn\'t technically the first time you see the shark in the film. You get a short glimpse of it in the pond scene.  Sorry about that. I am officially an asshole. Anyways Enjoy!\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\n\nClips used from:\n\nJaws-1975\nBack to the Future Part II-1989\nThe Strangers-2008\nSinister-2012\nHouse on Haunted Hill-1959\nInsidious-2010\nThe Conjuring 2-2016',
id: 'lYoYK761wwc',
uploaded: '"2017-01-14T22:25:35.000Z"',
duration: '"hours": 0, "minutes": 8, "seconds": 28',
title: 'Examining The Jump Scare: Case Study - Jaws (Ben Gardner\'s Boat)' },
{ videoUrl: 'https://www.youtube.com/watch?v=8GylHZDCaXM',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/8GylHZDCaXM/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/8GylHZDCaXM/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/8GylHZDCaXM/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/8GylHZDCaXM/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/8GylHZDCaXM/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'the-blackcoat-s-daughter-explained-and-the-art-of-restraint-in-a-horror-film',
description: 'This video is a little analysis on the film The Blackcoat\'s Daughter. I strongly suggest watching the film prior to watching this video because it is quite good and I would hate to spoil it for anyone. But if you have seen it and are looking to gain a better understanding of what makes this film work so well then go ahead and give this video a watch. Enjoy!\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: '8GylHZDCaXM',
uploaded: '"2018-03-08T21:38:46.000Z"',
duration: '"hours": 0, "minutes": 12, "seconds": 43',
title: 'The Blackcoat\'s Daughter Explained and the Art of Restraint in a Horror Film' },
{ videoUrl: 'https://www.youtube.com/watch?v=9PhJY8GY574',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/9PhJY8GY574/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/9PhJY8GY574/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/9PhJY8GY574/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/9PhJY8GY574/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/9PhJY8GY574/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'annabelle-what-happened-part-2-annabelle-creation',
description: 'The Annabelle saga continues with Part 2 in which I discuss Annabelle Creation. Spoilers ahead. Enjoy!\n\nAnnabelle Creation is owned by Warner Brothers Pictures\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: '9PhJY8GY574',
uploaded: '"2017-11-25T01:43:13.000Z"',
duration: '"hours": 0, "minutes": 23, "seconds": 32',
title: 'Annabelle What Happened!?  Part 2 (Annabelle Creation)' },
{ videoUrl: 'https://www.youtube.com/watch?v=q3qt8RzLT9Y',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/q3qt8RzLT9Y/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/q3qt8RzLT9Y/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/q3qt8RzLT9Y/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/q3qt8RzLT9Y/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/q3qt8RzLT9Y/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'anime-starter-pack-a-what-to-watch-guide-for-the-anime-newcomer',
description: 'New to anime? Here are 4 anime series to get you started on your anime journey.\n\nFollow Me On:\n\nInstagram: https://www.instagram.com/culleyrose89/\nTwitter: https://twitter.com/RainbowRose89',
id: 'q3qt8RzLT9Y',
uploaded: '"2016-12-07T03:21:26.000Z"',
duration: '"hours": 0, "minutes": 10, "seconds": 57',
title: 'Anime Starter Pack: A What To Watch Guide For The Anime Newcomer' },
{ videoUrl: 'https://www.youtube.com/watch?v=0bUqG8jP7ts',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/0bUqG8jP7ts/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/0bUqG8jP7ts/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/0bUqG8jP7ts/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/0bUqG8jP7ts/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/0bUqG8jP7ts/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'downhill-a-star-wars-story',
description: 'Welp here is my Star Wars Video finally. Enjoy!\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: '0bUqG8jP7ts',
uploaded: '"2018-08-10T06:01:36.000Z"',
duration: '"hours": 0, "minutes": 32, "seconds": 0',
title: 'Downhill - A Star Wars Story' },
{ videoUrl: 'https://www.youtube.com/watch?v=hwHaYj1jc7g',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/hwHaYj1jc7g/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/hwHaYj1jc7g/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/hwHaYj1jc7g/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/hwHaYj1jc7g/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/hwHaYj1jc7g/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'the-shape-of-success',
description: 'It warms my heart seeing the amount of love The Shape of Water has been getting so I decided to make a video highlighting one of my favorite film makers, Guillermo del Toro. Enjoy!\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'hwHaYj1jc7g',
uploaded: '"2018-01-25T00:16:19.000Z"',
duration: '"hours": 0, "minutes": 8, "seconds": 8',
title: 'The Shape of Success' },
{ videoUrl: 'https://www.youtube.com/watch?v=Bk-twkbFXxU',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/Bk-twkbFXxU/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/Bk-twkbFXxU/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/Bk-twkbFXxU/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/Bk-twkbFXxU/sddefault.jpg","width":640,"height":480}}',
uri: 'animated-films-aren-t-just-for-little-babies',
description: 'When Isao Takahata passed away earlier this year I decided to begin writing a video about how I felt about animation. More specifically, my desire for more filmmakers to make animated films that are not simply marketed towards children. I love animation and I am always annoyed when I hear someone comment that its only for little kids. So, I made this video discussing my thoughts on the matter. Enjoy!\n\nFollow Me On:\nTwitter: https://twitter.com/RainbowRose89\nFacebook: https://www.facebook.com/JessFlix/ \nInstagram: https://www.instagram.com/culleyrose89/',
id: 'Bk-twkbFXxU',
uploaded: '"2018-09-06T00:47:54.000Z"',
duration: '"hours": 0, "minutes": 11, "seconds": 16',
title: 'Animated Films Aren\'t Just For Little Babies' },
{ videoUrl: 'https://www.youtube.com/watch?v=L4MXKtyvmpE',
thumbnails: '{"default":{"url":"https://i.ytimg.com/vi/L4MXKtyvmpE/default.jpg","width":120,"height":90},"medium":{"url":"https://i.ytimg.com/vi/L4MXKtyvmpE/mqdefault.jpg","width":320,"height":180},"high":{"url":"https://i.ytimg.com/vi/L4MXKtyvmpE/hqdefault.jpg","width":480,"height":360},"standard":{"url":"https://i.ytimg.com/vi/L4MXKtyvmpE/sddefault.jpg","width":640,"height":480},"maxres":{"url":"https://i.ytimg.com/vi/L4MXKtyvmpE/maxresdefault.jpg","width":1280,"height":720}}',
uri: 'audition-in-case-you-haven-t-seen-it-valentine-s-day-recommendation',
description: 'Here\'s my movie recommendation for Valentine\'s Day. Enjoy :)\n\nFollow Me On:\n\nInstagram: https://www.instagram.com/culleyrose89/\nTwitter: https://twitter.com/RainbowRose89\n\nI Knew a Guy by Kevin MacLeod is licensed under a Creative Commons Attribution license (https://creativecommons.org/licenses/by/4.0/)\nSource: http://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100199\nArtist: http://incompetech.com/',
id: 'L4MXKtyvmpE',
uploaded: '"2017-02-14T04:57:04.000Z"',
duration: '"hours": 0, "minutes": 3, "seconds": 41',
title: 'Audition - In Case You Haven\'t Seen It - Valentine\'s Day Recommendation' } ]

let sortBy = (property) => {
    var sortOrder = 1;
    if (property[0] === "-") {
        sortOrder = -1;
        property = property.substr(1);
    }
    return function (b, a) {
        var result = (a[property] < b[property]) ? -1 : (a[property] > b[property]) ? 1 : 0;
        return result * sortOrder;
    }
}

let sort = (data) => {
    return data.sort(sortBy("uploaded"));
}

module.exports = sort;