service: jessflix-frontend

provider:
  name: aws
  runtime: nodejs8.10

functions:
  jessflix:
    handler: index.handler
    events:
      - http:
          path: /
          method: get
      - http:
          path: /{any+}
          method: get
